# Production serve stage using lightweight Nginx Alpine
FROM nginx:alpine

# Copy pre-built production distribution bundle
COPY dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

